services:
  prometheus:
    profiles:
      - all
      - monitoring_full
      - prometheus
    image: prom/prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-15d}'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9095:9090
    restart: ${RESTART_POLICY:-on-failure:3}
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prom_data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  grafana:
    profiles:
      - all
      - monitoring_full
      - grafana
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:3000
    restart: ${RESTART_POLICY:-on-failure:3}
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-grafana}
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -S http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Prometheus scrapers:
  node-exporter:
    profiles:
      - all
      - monitoring_full
      - node_exporter
    image: prom/node-exporter:latest
    hostname: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M

  kafka-exporter:
    profiles:
      - all
      - monitoring_full
      - kafka_exporter
    image: seglo/kafka-lag-exporter:0.8.2
    hostname: kafka-exporter
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      ROOT_LOG_LEVEL: ${ROOT_LOG_LEVEL:-WARN}
      KAFKA_LAG_EXPORTER_LOG_LEVEL: ${KAFKA_LAG_EXPORTER_LOG_LEVEL:-INFO}
      KAFKA_LAG_EXPORTER_KAFKA_LOG_LEVEL: ${KAFKA_LAG_EXPORTER_KAFKA_LOG_LEVEL:-ERROR}
    command:
      - '/opt/docker/bin/kafka-lag-exporter'
      - '-Dconfig.file=/opt/docker/conf/application.conf'
      - '-Dlogback.configurationFile=/opt/docker/conf/logback.xml'
    volumes:
      - ./monitoring/kafka-exporter:/opt/docker/conf
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:8000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M

  mongodb-exporter:
    profiles:
      - all
      - monitoring_full
      - mongodb_exporter
    image: percona/mongodb_exporter:0.43.1
    hostname: mongodb-exporter
    ports:
      - "9216:9216"
    environment:
      MONGODB_URI: mongodb://${MONGO_EXPORTER_USERNAME:-exporter}:${MONGO_EXPORTER_PASSWORD:-replace_me}@${MONGO_IP:-mongo}:27017/?authSource=admin&directConnection=true
    command:
      - '--web.listen-address=:9216'
      - '--collect-all'
      - '--mongodb.direct-connect=true'
      - '--discovering-mode'
      - '--log.level=warn'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:9216/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  prom_data:
  grafana_data: