services:
  deduplicator:
    profiles:
      - all
      - deduplicator
    build:
      context: jpo-deduplicator
      dockerfile: Dockerfile
      args:
        MAVEN_GITHUB_TOKEN: ${MAVEN_GITHUB_TOKEN:?error}
        MAVEN_GITHUB_ORG: ${MAVEN_GITHUB_ORG:?error}
    image: jpo-deduplicator:latest
    restart: ${RESTART_POLICY}
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:?error}
      spring.kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:?error}
    healthcheck:
      test: ["CMD", "java", "-version"]
      interval: 10s
      timeout: 10s
      retries: 20
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 3G
    depends_on:
      kafka:
        condition: service_healthy
        required: false
