global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100'
  - job_name: 'kafka-exporter'
    static_configs:
      - targets:
        - 'kafka-exporter:8000'
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: 
        - 'mongodb-exporter:9216'
    metrics_path: /metrics