name: jpo-utils

on: [pull_request, push]

jobs:  
  build_intersection_api:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.9-eclipse-temurin-21
      options: --user root
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/settings.xml') }}-${{ runner.os }}-java-21
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ runner.os }}-java-21
            ${{ runner.os }}-maven-${{ runner.os }}-java-21
            ${{ runner.os }}-maven

      - name: Install Dependencies
        env:
          MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
          MAVEN_GITHUB_ORG: ${{ github.repository_owner }}
        run: |
          cd $GITHUB_WORKSPACE/jpo-deduplicator/jpo-deduplicator
          mvn clean install -DskipTests -s ./settings.xml
          mvn dependency:go-offline -s ./settings.xml

      - name: Run tests
        env:
          MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
          MAVEN_GITHUB_ORG: ${{ github.repository_owner }}
        run: |
          cd $GITHUB_WORKSPACE/jpo-deduplicator/jpo-deduplicator
          mvn verify -s ./settings.xml

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: intersection-api-test-results
          path: $GITHUB_WORKSPACE/jpo-deduplicator/jpo-deduplicator/target/surefire-reports

      - name: Clean up
        run: |
          rm -rf $GITHUB_WORKSPACE/jpo-deduplicator/jpo-deduplicator/target