name: DockerHub Build and Push

on:
  push:
    branches: [ master, develop, release/*]
    tags:     [ "*" ] 
  workflow_dispatch:
jobs:
  dockerhub-jpo-jikkou:
    uses: usdot-jpo-ode/actions/.github/workflows/dockerhub.yml@main
    with:
      image: usdotjpoode/jpo-jikkou
      context: jikkou
      file: jikkou/Dockerfile.jikkou
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dockerhub-jpo-kafka-connect:
    uses: usdot-jpo-ode/actions/.github/workflows/dockerhub.yml@main
    with:
      image: usdotjpoode/jpo-kafka-connect
      context: kafka-connect
      file: kafka-connect/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
