# This workflow will only build for Pull Requests which are opened, changed , merged 
name: Docker build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [feature/update_docker_workflows]

jobs:
  dockerhub-jpo-jikkou:
    uses: usdot-jpo-ode/actions/.github/workflows/docker.yml@main
    with:
      context: jikkou
      file: jikkou/Dockerfile.jikkou

  dockerhub-jpo-kafka-connect:
    uses: usdot-jpo-ode/actions/.github/workflows/docker.yml@main
    with:
      context: kafka-connect
      file: kafka-connect/Dockerfile