name: "DockerHub Build and Push"

on:
  push:
    branches:
      - "develop"
      - "master"
      - "release/*"

jobs:  
  dockerhub-jpo-jikkou:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Replace Docker tag
        id: set_tag
        run: echo "TAG=$(echo ${GITHUB_REF##*/} | sed 's/\//-/g')" >> $GITHUB_ENV
          
      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: jikkou/Dockerfile.jikkou
          push: true
          tags: usdotjpoode/jpo-jikkou:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  dockerhub-jpo-kafka-connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Replace Docker tag
        id: set_tag
        run: echo "TAG=$(echo ${GITHUB_REF##*/} | sed 's/\//-/g')" >> $GITHUB_ENV
          
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: kafka-connect
          push: true
          tags: usdotjpoode/jpo-kafka-connect:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
